"""empty message

Revision ID: 41f229d6d1c6
Revises: 
Create Date: 2019-12-24 19:07:33.923840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f229d6d1c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('isDesigner', sa.Boolean(), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('design_folder', sa.String(length=128), nullable=True),
    sa.Column('image_path', sa.String(length=128), nullable=True),
    sa.Column('isApproved', sa.Boolean(), nullable=True),
    sa.Column('isRejected', sa.Boolean(), nullable=True),
    sa.Column('user_name', sa.Integer(), nullable=True),
    sa.Column('no_of_votes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_name'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('design_folder'),
    sa.UniqueConstraint('image_path')
    )
    op.create_table('relationship_table',
    sa.Column('user_name', sa.Integer(), nullable=False),
    sa.Column('designs_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['designs_id'], ['designs.id'], ),
    sa.ForeignKeyConstraint(['user_name'], ['user.username'], ),
    sa.PrimaryKeyConstraint('user_name', 'designs_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationship_table')
    op.drop_table('designs')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
